export const genderOptions = [
    { text: 'Male', value: 'Male' },
    { text: 'Female', value: 'Female' },
    { text: 'Undefined', value: 'Undefined' }
]

export const raceOptions = [
    { text: 'Human', value: 'Human' },
    { text: 'Unhuman', value: 'unHuman' },
    { text: 'Undefined', value: 'Undefined' }
]


export const alignmentOptions = [
    { text: 'Good', value: 'Good' },
    { text: 'Evil', value: 'Evil' },
    { text: 'Neutre', value: 'Neutre' }
]

export const universeOptions = [
    { text: 'Pokemon - Pokemon', value: 'Pokemon - Pokemon' },
    { text: 'Avatar - Avatar: The Last Airbender(2005-2008) and The Legend of Korra(2012-2014)', value: 'Avatar - Avatar: The Last Airbender(2005-2008) and The Legend of Korra(2012-2014)' },
    { text: 'Bayonetta - Bayonetta Universe', value: 'Bayonetta - Bayonetta Universe' },
    { text: 'Ben 10', value: 'Ben 10' },
    { text: 'Black Clover', value: 'Black Clover' },
    { text: 'Bleach', value: 'Bleach' },
    { text: 'Breath Of Fire Universe', value: 'Breath Of Fire Universe' },
    { text: 'C17S - Castlevania (Series 2017-)', value: 'C17S - Castlevania (Series 2017-)' },
    { text: 'Creepypasta - Creepypasta verse', value: 'Creepypasta - Creepypasta verse' },
    { text: 'Darkstalkers - Darkstalkers', value: 'Darkstalkers - Darkstalkers' },
    { text: 'DB - Dragon Ball Verse', value: 'DB - Dragon Ball Verse' },
    { text: 'DCAU - DC Animated Universe', value: 'DCAU - DC Animated Universe' },
    { text: 'DCeased - DCeased', value: 'DCeased - DCeased' },
    { text: 'DCEU - DC Extended Universe', value: 'DCEU - DC Extended Universe' },
    { text: 'DCSHG - DC Superhero Girls (2019- Tv Show)', value: 'DCSHG - DC Superhero Girls (2019- Tv Show)' },
    { text: 'DCUAOM - DC Universe Animated Original Movies', value: 'DCUAOM - DC Universe Animated Original Movies' },
    { text: 'Digimon - Digimon', value: 'Digimon - Digimon' },
    { text: 'Earth-13122 - LEGO Marvel Super Heroes Game Universe', value: 'Earth-13122 - LEGO Marvel Super Heroes Game Universe' },
    { text: 'Earth-2149 - Zombiverse', value: 'Earth-2149 - Zombiverse' },
    { text: 'Earth-616 - Prime Marvel Universe', value: 'Earth-616 - Prime Marvel Universe' },
    { text: 'Earth-928 - Marvel 2099', value: 'Earth-928 - Marvel 2099' },
    { text: 'EMCU - Extended Marvel Cinematic Universe (2000-2019 Movies)', value: 'Pokemon - Pokemon' },
    { text: 'Fairy Tail Verse', value: 'Fairy Tail Verse' },
    { text: 'FF IX - Final Fantasy IX', value: 'FF IX - Final Fantasy IX' },
    { text: 'FOTNS - Fist of The North Star (1995 Movie)', value: 'FOTNS - Fist of The North Star (1995 Movie)' },
    { text: 'Futures End - DC\'s Futures End', value: 'Futures End - DC\'s Futures End' },
    { text: 'GL 2011 - Green Lantern (2011 Movie)', value: 'GL 2011 - Green Lantern (2011 Movie)' },
    { text: 'Glorfindel (Goldhaired)', value: 'Glorfindel (Goldhaired)' },
    { text: 'GMW - GMod Monster World', value: 'GMW - GMod Monster World' },
    { text: 'GOE - Gods of Egypt (2016, Movie)', value: 'GOE - Gods of Egypt (2016, Movie)' },
    { text: 'Hazbinverse - Hazbin Hotel Universe', value: 'Hazbinverse - Hazbin Hotel Universe' },
    { text: 'Hellsing', value: 'Hellsing' },
    { text: 'Hulk 2003 - Hulk Movie by Ang Lee', value: 'Hulk 2003 - Hulk Movie by Ang Lee' },
    { text: 'HXH - Hunter X Hunter Verse', value: 'HXH - Hunter X Hunter Verse' },
    { text: 'Injustice - Injustice (2013-2017 Games and Comics)', value: 'Injustice - Injustice (2013-2017 Games and Comics)' },
    { text: 'Invincible', value: 'Invincible' },
    { text: 'JJBA - JoJo\'s Bizarre Adventure', value: 'JJBA - JoJo\'s Bizarre Adventure' },
    { text: 'John Hancock', value: 'John Hancock' },
    { text: 'Jujutsu Kaisen Universe', value: 'Jujutsu Kaisen Universe' },
    { text: 'Just Imagine - DC\'s Just Imagine', value: 'Just Imagine - DC\'s Just Imagine' },
    { text: 'KOF - King of Fighters', value: 'KOF - King of Fighters' },
    { text: 'LEGO - LEGO Cinematic Univers', value: 'LEGO - LEGO Cinematic Universe' },
    { text: 'MAU - Marvel Animated Universe', value: 'MAU - Marvel Animated Universe' },
    { text: 'MC - Minecraft', value: 'MC - Minecraft' },
    { text: 'MCU - Marvel Cinematic Universe', value: 'MCU - Marvel Cinematic Universe' },
    { text: 'MK - Mortal Kombat', value: 'MK - Mortal Kombat' },
    { text: 'ML - Mobile Legends Universe', value: 'ML - Mobile Legends Universe' },
    { text: 'MonsterVerse - MonsterVerse', value: 'MonsterVerse - MonsterVerse' },
    { text: 'MtG - Magic the Gathering', value: 'MtG - Magic the Gathering' },
    { text: 'Narnia - The Chronicles of Narnia', value: 'Narnia - The Chronicles of Narnia' },
    { text: 'Naruto - Naruto, shippuden, Boruto', value: 'Naruto - Naruto, shippuden, Boruto' },
    { text: 'New 52 - New 52', value: 'New 52 - New 52' },
    { text: 'Ninjago - Ninjago', value: 'Ninjago - Ninjago' },
    { text: 'OPM - One Punch Man', value: 'OPM - One Punch Man' },
    { text: 'PJO - Percy Jackson & the Olympians', value: 'PJO - Percy Jackson & the Olympians' },
    { text: 'Prime Earth - Prime DC Comics Universe', value: 'Prime Earth - Prime DC Comics Universe' },
    { text: 'Queen Metroid', value: 'Queen Metroid' },
    { text: 'Rebirth - DC-Rebirth', value: 'Rebirth - DC-Rebirth' },
    { text: 'Record Of Ragnarok', value: 'Record Of Ragnarok' },
    { text: 'Sailor Moon - Sailor Moon', value: 'Sailor Moon - Sailor Moon' },
    { text: 'Seven Deadly Sins Universe', value: 'Seven Deadly Sins Universe' },
    { text: 'Shaman King Verse', value: 'Shaman King Verse' },
    { text: 'Smallville - Smallville (2001-2011 TV Series)', value: 'Smallville - Smallville (2001-2011 TV Series)' },
    { text: 'Sonic', value: 'Sonic' },
    { text: 'SotM - Sentinels of the Multiverse', value: 'SotM - Sentinels of the Multiverse' },
    { text: 'Soul Eater - Soul Eater Universe', value: 'Soul Eater - Soul Eater Universe' },
    { text: 'Star Wars - Star Wars Universe', value: 'Star Wars - Star Wars Universe' },
    { text: 'SWL - Star Wars: Legends Multiverse', value: 'SWL - Star Wars: Legends Multiverse' },
    { text: 'Teen Titans - Teen Titans (2003-2006 TV Series)', value: 'Teen Titans - Teen Titans (2003-2006 TV Series)' },
    { text: 'Tekken - Tekken', value: 'Tekken - Tekken' },
    { text: 'Toho - Toho Expanded Universe', value: 'Toho - Toho Expanded Universe' },
    { text: 'TT - Tiny Titans', value: 'TT - Tiny Titans' },
    { text: 'Universo Classico - Universo Classico Bonelli', value: 'Universo Classico - Universo Classico Bonelli' },
    { text: 'USU - Ultra Series Universe', value: 'USU - Ultra Series Universe' },
    { text: 'Wakfu - wakfu', value: 'Wakfu - wakfu' },
    { text: 'William Joseph Blazkowicz III', value: 'William Joseph Blazkowicz III' },
    { text: 'Willverse - Abidan Archives', value: 'Willverse - Abidan Archives' },
    { text: 'Wings Of Fire Universe', value: 'Wings Of Fire Universe' },
    { text: 'WoT - Wheel of Time', value: 'WoT - Wheel of Time' },
    { text: 'WotT - Wrath of the Titans', value: 'WotT - Wrath of the Titans' },
    { text: 'Young Justice - Young Justice (2010- TV Series)', value: 'Young Justice - Young Justice (2010- TV Series)' },
    { text: 'Yu Yu Hakusho Verse', value: 'Yu Yu Hakusho Verse' }

]